### ISSUE TITLE
[disccus]:What are the similarities and differences with other similar plugins, and what are the core features?

### ISSUE THREAD

**Issue by windily-cloud** [aptend/typing-transformer-obsidian#26]
这插件很不错，我非常喜欢增强编辑的插件。但我发现您的插件很多功能貌似都被很好的实现了。

比如自动补全，latex suite插件支持自动，tab触发，光标定位，选择后补全，正则补全，未来还会支持自定义函数补全。

比如中英文自动添加空格，linter插件就能很好的做到，内置大量格式规则，也可以自己编写linter规则。

所以我看到您的插件很激动也很疑惑。未来该插件和这些插件的异同在哪？核心特性又是什么呢？

衷心感谢您的开源工作以及任何回复!!!

**Comment by aptend** [comment]
Hello，Cloud，感谢你的问题。这两个插件我之前都还没用过，现在简单使用了一下，确实又帅又全面 😸 ，谢谢推荐。总体来说，宏观目标是一致的，似乎有这些细节差别:

自动补全的触发机制不同，latex-suite 触发时默认光标在 trigger 字符串的结尾处，但是当前插件则可以指定，比如在一对书名号中间再输入一个书名号，会变为小于符号，`'《《|》' -> '<|'`。 

对于自动加空格，我的想法是
1. linter、easytyping 都是基于正则，不过对我而言，正则可太不好读写了，堪比 brainf*ck 语言 😂  ，所以我用 [pest](https://pest.rs/) 来编写 block 定义，排版操作也变为给 block 之间加空格，这样的实现可能更好维护一些。当然这个策略还需要未来更多的验证
1. 当前插件所处理的场景，是一边输入一边自动排版，并且把排版范围缩小，甚至小于一行。这样即使自动排版出错，可以及时手动干预，而且修改不被后续自动排版影响。而 linter 则是一把梭，或者选中再排版，使用场景可能不太一样。

回到你的问题，异同在哪？坦白讲大同小异，当前插件更多的是针对我自己的一些使用习惯和偏好，然后做了一丢丢的延展。核心特性？从产品角度很难提炼出一个有强烈宣传效果的说法，可能主要还是体现在上面提到的差别中：希望能减少按 shift 切换输入法的次数以及能写入时自动排版，并且附带把我的一些技术想法进行实践。

总之非常理解你的困惑，初看上去这个插件的功能都可以用现有工具实现，不过在我看来还是有一些区别在的，开源也是希望当前插件的小改动能帮助和我有相似编辑习惯的人。

**Comment by windily-cloud** [comment]
>自动补全的触发机制不同，latex-suite 触发时默认光标在 trigger 字符串的结尾处，但是当前插件则可以指定，比如在一对书名号中间再输入一个书名号，会变为小于符号，'《《|》' -> '<|'。

latex-suite也能指定，tab跳转到下一个光标处。

> 当前插件更多的是针对我自己的一些使用习惯和偏好，然后做了一丢丢的延展。

的确，自己实现的话自由度高一点，想干嘛就干嘛，就是自己开发维护挺麻烦的。我已领会到你的想法，ob不就是需要打造成符合自己工作流的工具嘛，感谢你的分享，给了社区更多的可能性！
