### ISSUE TITLE
[HELP] Line numbers markers is not aligned with the rule content if reopen the settings tab

### ISSUE THREAD

**Issue by aptend** [aptend/typing-transformer-obsidian#27]
![not aligned linenumbers](https://user-images.githubusercontent.com/49832303/179382322-eed9c6cb-b4e0-46f7-95d2-8feaf67be191.png)

this problem will disappear if resizing the window or adding a line to the content……

https://github.com/aptend/typing-transformer-obsidian/blob/7de8bb724ac052784453d2cbf785bb0a7295c477/src/settings.ts#L133

**Comment by caasion** [comment]
I'm not sure how to reproduce this issue. Could you elaborate a little more (like when it happens, how to make it happen etc.)? I think it would help me or others.

**Comment by aptend** [comment]
OS: Window 10
version: Obsidian 0.15.9

Reproduce:
1. Open Obsidian, and open settings
2. Click Typing Transformer settings tab in Community Plugins section, this time, rule editor line numbers are aligned.
3. Close Obsidian settings directly
4. Open Obsidian settings again, the displayed view is Typing Transformer settings tab, and this time, rule editor line numbers are NOT aligned

repeat step 3 and 4 to see the issue repeatedly

**Comment by caasion** [comment]
Hmm. I'm on ubuntu, same Obsidian version, but I'm not able to reproduce it. It might be a windows thing. 

Btw, have you made sure to disable all themes and css snippets to make sure they are not the culprit?

**Comment by aptend** [comment]
Thanks for the very valuable information! After a few trials, the problem seems to be related to the theme I'm using...

I'm closing this issue
