### ISSUE TITLE
Colours Used in Rule Editor are Incorrect

### ISSUE THREAD

**Issue by iamrecursion** [aptend/typing-transformer-obsidian#30]
First up I want to say a huge thanks for this plugin! It's brilliant, and something that I've found absolutely indispensible!

I'm having an issue where the colours used in the rule editor don't conform to the active theme. In my case I'm on a dark theme:

- The gutter with the line numbers use light colours, consisting of a white background and grey text.
- The cursor uses an illegible very dark grey colour.

<img width="699" alt="image" src="https://user-images.githubusercontent.com/5780639/182004387-e9903d02-51c6-4f61-82bc-8a814d8f1fcf.png">

**Comment by aptend** [comment]
Thanks for your feedback! This problem has been fixed in version 0.2.2, please update the plugin and have a try

![image](https://user-images.githubusercontent.com/49832303/182007227-ade6cc30-f597-4cc6-b4dc-c674ea84a1dd.png)

**Comment by iamrecursion** [comment]
That's fixed it! Thank you so much!
