### ISSUE TITLE
[FR] Multiple characters in "Selection Insert Rules"

### ISSUE THREAD

**Issue by caasion** [aptend/typing-transformer-obsidian#32]
Hello,

I'm finding a lot of uses for this plugin, but there is a limitation that I hope could be resolved through this feature.

I would like to allow for multiple characters in "Selection Insert Rules". I am trying to insert surround selected text that only gets converted when `(` + `<` are typed, but the plugin doesn't allow for multiple characters in such rules.

[`'(<' -> '⟨' + '⟩'`] is illegal.

I really hope that you could implement this because it would allow for more flexibility.

**Comment by aptend** [comment]
hmm……I'm afraid this can't be done in the near future, because the plugin can't know when you will type the second char, it is a little tricky. I wound recommand to use a special char to replace `(<` , like a, b, c, d anyone you like 🤷

**Comment by caasion** [comment]
Perhaps there could be a configured key(s) that you hold (eg. `tab`, or 'alt' + 'tab') that works when text is selected, and then you will get a text input where you can type a string. Once you let go, it will look at what is typed, evaluate it, and add whatever characters.

Maybe this is making the plugin too complicated lol... but just an idea.

**Comment by caasion** [comment]
Resolved with this commit:
[feat: insert multiple char on side](https://github.com/aptend/typing-transformer-obsidian/commit/fed3fea6153649188c65fe519abece06f2b4d2bb)
