### ISSUE TITLE
[Feature Request] Make the rules editor resizable

### ISSUE THREAD

**Issue by caasion** [aptend/typing-transformer-obsidian#35]
Hello. It's me again :P 

I think it would be really helpful if the rules editor in the settings tab:
![image](https://user-images.githubusercontent.com/103465188/183313023-521c7874-897f-49fd-9478-e5389918e068.png)
is resizable.

This make people with more vertical space's editing easier.

**Comment by aptend** [comment]
OK, looks like it could be implemented in css 🤔 

Do you mind that the size of editor restores to the default if reopen the settings tab?

**Comment by caasion** [comment]
for now, I think that is a good idea since you will probably need to save values and stuff if the size stays the same. anyhow, you could implement it sometime in the future (but i don't think its a high priority)

**Comment by aptend** [comment]
In next release you can grab this corner to expand the editor vertically 🥳 

![image](https://user-images.githubusercontent.com/49832303/183655791-5886e783-73f8-46a1-8f8c-700a589e1bcf.png)

**Comment by caasion** [comment]
I saw this in your commits. It works very well!
