### ISSUE TITLE
[FR] Toggling Conversion and Profiles

### ISSUE THREAD

**Issue by caasion** [aptend/typing-transformer-obsidian#42]
### 1 - Toggling All Conversion
On a basic level, I think it would be useful to toggle the conversion of the plugin without having to disable the plugin entirely or delete/comment the conversion rules. Preferably, there is a command (+ hotkey) and optionally a ribbon icon that does this.

It would look something like this (except the toggle is properly aligned :P)
![image](https://user-images.githubusercontent.com/103465188/184453359-eefe937b-d44d-477d-8f39-6f6d6780be48.png)

OR

![image](https://user-images.githubusercontent.com/103465188/184453621-d652b4fb-a717-4dfe-a908-06715b0a2017.png)
(both implemented without the actual functionality)

---
### 2 - Disabling certain types conversion rules

Diving a little deeper, It would be nice to be able to disable certain conversion rules.
And for this, I think it would be something that is toggled through plugin settings. 

For it to be more intuitive, it could be available through a GUI by clicking a ribbon icon or another command. I don't think it would be ideal to have a bunch of commands for toggling these individually.

---
### 3 - Profiles
Finally, the most ultimate form of this FR is to have profiles. There will be different profiles with their own respective rules. You can switch between them.

In the settings, there will be buttons that act like tabs, and there will be a different editor instance opened for each:
![Example of tabs](https://gist.github.com/sailKiteV/e1124244161e2ab5ac3045562beee4ae/raw/fd8176c836554ca35ff48fbce78c48802acc15cb/Obsidian_KCCuJa4T0o.gif)
(this is what the tabs would look like (source: sailKiteV's tabs CSS))

Again, there would be a menu (activated by commands or a ribbon icon) that lets you choose/cycle between the different profiles. 

Optionally, you can bind commands specifically to switch to a certain profile.

Optionally, they will have their own settings for disabling certain types conversion rules, but tbh this feature isn't all that necessary.

**Comment by aptend** [comment]
My idea about this is marking different profiles using comments and selecting one of them to apply, like ——

<img src=https://user-images.githubusercontent.com/49832303/184476154-7e4292ca-f90a-4747-9e6f-b544a5aba923.png width=700 />

I guess it is easier to implement than managing multiple tabs, but I might be wrong considering my limited frontend experience. 👶 

Btw, I'm curious what is the original motivation to have multiple profiles to switch? Can you describe some scenes?

**Comment by caasion** [comment]
I thought whether if it is possible to detect if you are writing a codeblock. There are some formatting and transformation you don't want to do when you are typing in a codeblock. However, I don't think it is possible for this detection, so I thought of asking for profiles.

Multiple profiles would be especially useful for different scenarios such as when you are in a code block or using latex. When using latex, I want to convert `1/2` into `\frac{1}{2}`, but normally, I don't want to convert this.

This functionality also gives you flexibility when you are writing different kinds of things. For example, if I want to write a formal text, I would want to convert things like `idc` into `I don't care`, but if I am writing in my journal, I want to keep the casual tone.

I think having profiles to switch from will be a lot more flexible than other implementations (such as certain rules will be applied if file has tag, if file is linked to... etc.)

Also, I want to request for "global rules". These are rules that are applied no matter which profile you are in, so you don't need to copy and paste them to every profile.

**Comment by caasion** [comment]
> My idea about this is marking different profiles using comments and selecting one of them to apply, like ——
> 
> <img alt="" width="700" src="https://user-images.githubusercontent.com/49832303/184476154-7e4292ca-f90a-4747-9e6f-b544a5aba923.png">
> 
> I guess it is easier to implement than managing multiple tabs, but I might be wrong considering my limited frontend experience. 

Honestly, I think this will work well. I think you should focus on the feature, then you can optimize it/style it better afterwards.

Thank you for considering my FR!

**Comment by caasion** [comment]
> ### 2 - Disabling certain types conversion rules
> 
> Diving a little deeper, It would be nice to be able to disable certain conversion rules. And for this, I think it would be something that is toggled through plugin settings.
> 
> For it to be more intuitive, it could be available through a GUI by clicking a ribbon icon or another command. I don't think it would be ideal to have a bunch of commands for toggling these individually.

For the second item in this FR, I think you could reference the interface of easy typing:

![image](https://user-images.githubusercontent.com/103465188/184500385-80a8764c-f41d-4495-ba98-8cd5b5f3f4eb.png)

**Comment by aptend** [comment]
> > ### 2 - Disabling certain types conversion rules
> > Diving a little deeper, It would be nice to be able to disable certain conversion rules. And for this, I think it would be something that is toggled through plugin settings.
> > For it to be more intuitive, it could be available through a GUI by clicking a ribbon icon or another command. I don't think it would be ideal to have a bunch of commands for toggling these individually.
> 
> For the second item in this FR, I think you could reference the interface of easy typing:

sry, I don't get it now. What does 'certain types' mean, any examples? Is it an option to comment them out? 
In my early understanding, if the third item is implemented, the second item can be ignored. What is the relation between the second and third items?

**Comment by aptend** [comment]
> The idea came up when I thought whether if it is possible to detect if you are writing a codeblock. There are some formatting and transformation you don't want to do when you are typing in a codeblock. However, I don't think it is possible for this detection, so I thought of asking for profiles.

Actually it is possible and easy to detect if you are typing in a codeblock、math block, this is even used in the space-inserting feature. But, I think it is nice to split rules into parts and let users combine/select them freely. Also, I'd like to take the opportunity to implement this feature and learn a little bit about frontend frameworks :D

> Also, I want to request for "global rules". These are rules that are applied no matter which profile you are in, so you don't need to copy and paste them to every profile.

Yeah, this is reasonable.

**Comment by caasion** [comment]
> > > ### 2 - Disabling certain types conversion rules
> > > Diving a little deeper, It would be nice to be able to disable certain conversion rules. And for this, I think it would be something that is toggled through plugin settings.
> > > For it to be more intuitive, it could be available through a GUI by clicking a ribbon icon or another command. I don't think it would be ideal to have a bunch of commands for toggling these individually.
> > 
> > 
> > For the second item in this FR, I think you could reference the interface of easy typing:
> 
> sry, I don't get it now. What does 'certain types' mean, any examples? Is it an option to comment them out? In my early understanding, if the third item is implemented, the second item can be ignored. What is the relation between the second and third items?

Actually, you're right :rofl:. I think this feature would just clutter the plugin and make it more confusing :P. So please don't implement it.

**Comment by aptend** [comment]
Hi @caasion, please take a look at #52 , I have implemented profiles. It would be nice if you can help testing it. 
Oh, don't forget to copy the new styles.css after building the plugin

**Comment by aptend** [comment]
#56 and #57 were done.
