### ISSUE TITLE
[Bug] Weird behavior if I put multiple characters in trigger of selection insert

### ISSUE THREAD

**Issue by caasion** [aptend/typing-transformer-obsidian#47]
Watch the video:
[Screencast from 2022-08-17 06:36:03 PM.webm](https://user-images.githubusercontent.com/103465188/185255861-3df5eefb-cd50-4b5c-aa75-5d4a9f272bac.webm)

Notes:

- This behavior occurs to every character I enter.
- When I go back into plugin settings, the incorrect rule is replaced, but I still get errors and am unable to type.
- Issue is solved when I `Reload App Without Saving`

**Comment by aptend** [comment]
so weird, Obsidian v0.15.9? I'm not able to reproduce it on MacOS

> When I go back into plugin settings, incorrect rule is replaced, but I still get errors and am unable to type.

'replaced' means the rule editor is empty? 
'errors' means rule editor errors is still displayed in the settings tab? 
'unable to type' can you delete or click other buttons and get repsonse?

**Comment by caasion** [comment]
Yes, obsidian 0.15.9

1. Yes, or it is reverted back to the older version.
2. Error means error in console, the one that is shown in the video
3. Clarification: Any select insert becomes weird, but I can still type.

[Screencast from 2022-08-18 08:23:34 AM.webm](https://user-images.githubusercontent.com/103465188/185393950-b23fba34-603c-467b-a953-b732bf5e48f2.webm)

**Comment by caasion** [comment]
it looks like my video recording is broken :grimacing:

I'm really sorry! :sweat: 

Let me record another one with the actual errors.

**Comment by caasion** [comment]
![error](https://user-images.githubusercontent.com/103465188/185435453-a1282141-045f-42a4-9146-1c4f0dadb491.gif)
 
This time I have truly captured the error. 

I'm really sorry for the confusion😬 

I hope this can help

**Comment by aptend** [comment]
👏 Yes, this error is what I have seen. pr #48 already fixed it, I merge it now and you can try again
