### ISSUE TITLE
[BUG] Weird Priorities with Conversion Rules

### ISSUE THREAD

**Issue by caasion** [aptend/typing-transformer-obsidian#49]
Plugin Version: 3.0.0
Obsidian Version: v0.15.9

I am trying to move out of the asterisks when I hit `*` and there is `**` ahead. The use of this would be to move out of bolding when I am at the asterisks.

I have these following rules:
```coffeescript
'*|**' -> '**|' # move out of asterisks
'*|' -> '*|*' # auto-pair
```

![error](https://user-images.githubusercontent.com/103465188/186429556-aabf8795-bce9-427c-aa90-010109eb8392.gif)

However, what happens in this gif is that the auto-pair takes over and the "move out of asterisks" doesn't work. I suspect that either I did something wrong with the rule or there is something wrong with the priorities of the rules.

**Comment by aptend** [comment]
If you want to move out of asterisks by hitting two `*`,  try following rules
```python
'**|*' -> '**|' # move out of asterisks
'*|' -> '*|*' # auto-pair
```

**Comment by caasion** [comment]
My intent is to be able to move out of 2 asterisks by hitting one `*`. Is that possible in anyway? I don't want to move out when there is one asterisk because it would only allow for a italic font but not a bold font.

**Comment by aptend** [comment]
> My intent is to be able to move out of 2 asterisks by hitting one `*`

sorry I don't get it, could you give me more detailed examples?

I guess you want to keep the auto pair rule, right? say, we now hit one `*` and get `*|*`, then what's next?

**Comment by caasion** [comment]
So we have `*|*` right one, which won't do anything yet, but when we hit one `*` again, we get `**|**`. 

Afterwards, I type some text inside and get `**abc|**`. Now, when I hit `*` again, I want to move out of both of the asterisks and get `**abc**|`

Without the auto-pair rule, I can go from `|**` to `|**` by hitting one `*` with this rule:
```coffeescript
'*|**' -> '**|'
```
but when the rules are like this:
```coffeescript
'*|**' -> '**|'
'*' -> '*|*'
```
the first rule doesn't work properly anymore

**Comment by aptend** [comment]
Ah, it is a bug, let me fix it
