### ISSUE TITLE
[FR/Suggestion] Using Coffeescript for syntax highlighting

### ISSUE THREAD

**Issue by caasion** [aptend/typing-transformer-obsidian#50]
I pasted my rules into VSCode and noticed that it automatically viewed it as coffescript. I noticed that the syntax highlighting of this language is much better compared to python. This is how it looks in VSCode.

![image](https://user-images.githubusercontent.com/103465188/186515493-1f5652e3-c8c2-4995-aa3b-ef567c393041.png)

**Comment by aptend** [comment]
There seems no published `@codemirror/lang-coffeescript` package to use…… I'd like to try writing our own syntax highlighting in the future, but is has lower priority
