### ISSUE TITLE
[BUG] Deletion rules ignore non-trigger characters in rule

### ISSUE THREAD

**Issue by caasion** [aptend/typing-transformer-obsidian#51]
Plugin Version: 3.0.0
Plugin Version: 0.15.9

I have this rule:
```coffeescript
'[|]' -x '|'
```
but this deletion rule triggers when I have `'[|'`, and deletes whatever character is after.

For example, when I have `'[|['` and when I delete it, it removes both of the `[`, when the rule shouldn't even trigger at all.

**Comment by aptend** [comment]
I have reproduced this promblem, I will fix soon, thank you

**Comment by aptend** [comment]
this is fixed in https://github.com/aptend/typing-transformer-obsidian/commit/afe08c8ff4edc24e806d4f5bd3313a231b8bd54f, after #46 is merged, I will a patch 0.3.1
