### ISSUE TITLE
[BUG] When converting to an emoji, cursor is shifted one character back.

### ISSUE THREAD

**Issue by caasion** [aptend/typing-transformer-obsidian#72]
[Screencast from 2023-09-09 12-33-03.webm](https://github.com/aptend/typing-transformer-obsidian/assets/103465188/60520106-c24e-4703-87cf-7eced752bea1)

In my conversion rules, each result has the cursor placed after the space. However, for emojis after conversion, the cursor is place in between the emoji and the space, not after it.

**Comment by aptend** [comment]
LONG TIME! 
Indeed, the code was not correctly handling characters with multiple Unicode units. I am currently addressing this issue.
