### ISSUE TITLE
Hopefully this will work in EXcalidraw as well

### ISSUE THREAD

**Issue by jiajiala** [aptend/typing-transformer-obsidian#73]
Hopefully this will work in EXcalidraw as well

**Comment by aptend** [comment]
I haven't used the Excalidraw plugin extensively; so far, I've only been creating some simple drawings without incorporating too many advanced features.

Could you clarify the specific purpose of this request? Are you planning to edit Markdown files within Excalidraw? Adding examples with pictures or animations would be greatly appreciated!

**Comment by jiajiala** [comment]
![image](https://github.com/user-attachments/assets/77960762-4625-438c-aaf8-7e7fce2d7f7f)

本来是想在EXcalidraw中的双击文字输入也能使用快捷输入的，但是感觉不太现实，
它的实现与markdown太不一样的，完全两个系统
还是不麻烦大佬了
