### ISSUE TITLE
[BUG]:styles.css affects the MD edit in the canvas, making the MD blur when editing

### ISSUE THREAD

**Issue by jiajiala** [aptend/typing-transformer-obsidian#76]
![image](https://github.com/aptend/typing-transformer-obsidian/assets/73203026/cabfed9f-31cd-4d80-8e77-c4d584f9e149)
In the picture, on the left is the effect when typing-transformer is opened, which becomes fuzzy

**Comment by jiajiala** [comment]
![image](https://github.com/aptend/typing-transformer-obsidian/assets/73203026/826e97f4-33a0-4593-8e47-ab476ee1caee)
I screened it. It's the effect of the blurring

**Comment by aptend** [comment]
Thank you so much! I couldn't have found the cause without your attention to detail.

**Comment by jiajiala** [comment]
> Thank you so much! I couldn't have found the cause without your attention to detail.太感谢了！如果没有你对细节的关注，我不可能找到原因。

谢谢大佬的插件才是！！
