### ISSUE TITLE
Cannot add literal new line `\n` character

### ISSUE THREAD

**Issue by zanodor** [aptend/typing-transformer-obsidian#78]
If one adds `\\n`, it is not interpreted as a `\n` escaped: it will print a backslash at the end of the line and then effect a new line.  
Any hope of adding this scoping? This is handy when pasting plantUML sample diagrams through text expansion and adding line breaks in longer explanatory labels, for instance. Single quote and pipe characters are successfully escaped though.

Cheers

**Comment by ceswap** [comment]
I have the same problem, it seems the backslash character cannot be escaped on its own.

**Comment by aptend** [comment]
Hi guys! I think I have understood the situation.
And this pr #79 has seemed like a solution, why was it closed? 
Based on #79, I guess the rule like `'-n|' -> '\\\\n|'` will work, won't it?

**Comment by ceswap** [comment]
> Hi guys! I think I have understood the situation.
> 
> And this pr #79 has seemed like a solution, why was it closed? 
> 
> Based on #79, I guess the rule like `'-n|' -> '\\\\n|'` will work, won't it? 

Hey, sorry it's my fault, I thought I was comiting to my forked version, but I submitted the PR, but I haven't tested anything and I have no experience with obsidian plugins 😅

**Comment by aptend** [comment]
@ceswap I've tested your PR on my local machine with the rule `'-n| -> \\n'`, and it functions well! Would you like to reopen your PR, become a contributor, and take the credit?

code change:
<img width="527" alt="image" src="https://github.com/user-attachments/assets/845317f0-ef16-452d-a262-2d4516ebca79">

the rule:
<img width="527" alt="image" src="https://github.com/user-attachments/assets/388f650a-b34b-42b6-8963-579d25da7910">

effect:

https://github.com/user-attachments/assets/9ad24a62-6009-483f-a344-9d4e69c35f94

**Comment by ceswap** [comment]
Thanks for your testing! I have reopened the PR, feel free to make any change you feel necessary.

**Comment by aptend** [comment]
> Could you add the changes to a release we could download, beta or otherwise? Cheers

0.4.1 is coming soon, probably this week. I’m just fixing another bug.
